### PR TITLE
Remove warnings from terminal when compiling the test runner.

### LINKED ISSUE #83: Fix warnings reported when compiling the test runner
There's a bunch of warnings reported by the compiler. It would be nice if we address them.

```
dotnet-bunny/Turkey/DotNet.cs(162,30): warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Cleaner.cs(39,27): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Cleaner.cs(56,27): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/NuGet.cs(28,33): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/NuGet.cs(38,35): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/ProcessExtensions.cs(50,47): warning CS0168: The variable 'ex' is declared but never used [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestOutputFormat.cs(81,40): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestOutputFormat.cs(94,40): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestOutputFormat.cs(16,40): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestOutputFormat.cs(22,40): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestOutputFormat.cs(51,40): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestRunner.cs(47,35): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestRunner.cs(48,35): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestRunner.cs(49,35): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestRunner.cs(50,35): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestRunner.cs(51,35): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestParser.cs(18,54): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestOutputFormat.cs(14,22): warning CA1034: Do not nest type NewOutput. Alternatively, change its accessibility so that it is not externally visible. (https://msdn.microsoft.com/en-us/library/ms182162.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestOutputFormat.cs(12,18): warning CA1052: Type 'TestOutputFormats' is a static holder type but is neither static nor NotInheritable (http://msdn.microsoft.com/library/ms182168.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestOutputFormat.cs(57,22): warning CA1034: Do not nest type JUnitOutput. Alternatively, change its accessibility so that it is not externally visible. (https://msdn.microsoft.com/en-us/library/ms182162.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Program.cs(15,18): warning CA1052: Type 'Program' is a static holder type but is neither static nor NotInheritable (http://msdn.microsoft.com/library/ms182168.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Test.cs(21,29): warning CA2227: Change 'IgnoredRIDs' to be read-only by removing the property setter. (https://msdn.microsoft.com/library/ms182327.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Test.cs(22,29): warning CA2227: Change 'SkipWhen' to be read-only by removing the property setter. (https://msdn.microsoft.com/library/ms182327.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestRunner.cs(25,52): warning CA1051: Do not declare visible instance fields (https://msdn.microsoft.com/en-us/library/ms182141.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/XUnitTest.cs(19,37): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/XUnitTest.cs(20,37): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/BashTest.cs(41,34): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/CsprojCompatibilityPatcher.cs(13,23): warning CA1822: Member Patch does not access instance data and can be marked as static (Shared in VisualBasic) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Cleaner.cs(39,27): warning CA1822: Member CleanProjectLocalDotNetCruftAsync does not access instance data and can be marked as static (Shared in VisualBasic) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Cleaner.cs(85,17): warning CA1307: The behavior of 'string.StartsWith(string)' could vary based on the current user's locale settings. Replace this call in 'Turkey.Cleaner.ExpandPath(string)' with a call to 'string.StartsWith(string, System.StringComparison)'. (https://msdn.microsoft.com/en-us/library/bb386080.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Cleaner.cs(83,36): warning CA1822: Member ExpandPath does not access instance data and can be marked as static (Shared in VisualBasic) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/DotNet.cs(46,40): warning CA1307: The behavior of 'string.StartsWith(string)' could vary based on the current user's locale settings. Replace this call in 'Turkey.DotNet.RuntimeVersions.get' with a call to 'string.StartsWith(string, System.StringComparison)'. (https://msdn.microsoft.com/en-us/library/bb386080.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/DotNet.cs(140,26): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/IEnumerableExtensions.cs(13,23): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/NuGet.cs(24,32): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/NuGet.cs(25,26): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/PlatformId.cs(21,27): warning CA1308: In method 'ComputePlatformIds', replace the call to 'ToLowerInvariant' with 'ToUpperInvariant'. (https://msdn.microsoft.com/en-us/library/bb386042.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/PlatformId.cs(66,24): warning CA1822: Member GetValue does not access instance data and can be marked as static (Shared in VisualBasic) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/PlatformId.cs(76,17): warning CA1307: The behavior of 'string.StartsWith(string)' could vary based on the current user's locale settings. Replace this call in 'Turkey.PlatformId.Unquote(string)' with a call to 'string.StartsWith(string, System.StringComparison)'. (https://msdn.microsoft.com/en-us/library/bb386080.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/PlatformId.cs(76,42): warning CA1307: The behavior of 'string.EndsWith(string)' could vary based on the current user's locale settings. Replace this call in 'Turkey.PlatformId.Unquote(string)' with a call to 'string.EndsWith(string, System.StringComparison)'. (https://msdn.microsoft.com/en-us/library/bb386080.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/PlatformId.cs(71,24): warning CA1822: Member Unquote does not access instance data and can be marked as static (Shared in VisualBasic) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/PlatformId.cs(84,25): warning CA1822: Member GetLddVersion does not access instance data and can be marked as static (Shared in VisualBasic) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/ProcessExtensions.cs(15,19): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/NuGet.cs(31,40): warning CA1307: The behavior of 'Newtonsoft.Json.Linq.JObject.GetValue(string?)' could vary based on the current user's locale settings. Replace this call in 'Turkey.NuGet.IsPackageLiveAsync(string, Turkey.Version, string)' with a call to 'Newtonsoft.Json.Linq.JObject.GetValue(string?, System.StringComparison)'. (https://msdn.microsoft.com/en-us/library/bb386080.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/NuGet.cs(33,29): warning CA1307: The behavior of 'string.Equals(string?)' could vary based on the current user's locale settings. Replace this call in 'Turkey.NuGet.IsPackageLiveAsync(string, Turkey.Version, string)' with a call to 'string.Equals(string?, System.StringComparison)'. (https://msdn.microsoft.com/en-us/library/bb386080.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/NuGet.cs(28,33): warning CA1822: Member IsPackageLiveAsync does not access instance data and can be marked as static (Shared in VisualBasic) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/NuGet.cs(24,32): warning CA2234: Modify 'NuGet.IsPackageLiveAsync(string, Version)' to call 'HttpClient.GetStringAsync(Uri)' instead of 'HttpClient.GetStringAsync(string)'. (https://msdn.microsoft.com/en-us/library/ms182360.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/SourceBuild.cs(19,23): warning CA1055: Change the return type of method SourceBuild.GetBranchContentUrl(Version) from string to System.Uri. (https://msdn.microsoft.com/en-us/library/ms182176.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/SourceBuild.cs(19,23): warning CA1822: Member GetBranchContentUrl does not access instance data and can be marked as static (Shared in VisualBasic) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Version.cs(137,13): warning CA1065: GetHashCode creates an exception of type Exception. Exceptions should not be raised in this type of method. If this exception instance might be raised, change this method's logic so it no longer raises an exception. (https://msdn.microsoft.com/en-us/library/bb386039.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/ProcessExtensions.cs(46,23): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/SourceBuild.cs(44,33): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/SourceBuild.cs(46,40): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/SourceBuild.cs(63,37): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/NuGet.cs(41,23): warning CA2208: Call the ArgumentNullException constructor that contains a message and/or paramName parameter. (https://msdn.microsoft.com/en-us/library/ms182347.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/NuGet.cs(69,31): warning CA1307: The behavior of 'string.Replace(string, string?)' could vary based on the current user's locale settings. Replace this call in 'Turkey.NuGet.GenerateNuGetConfig(System.Collections.Generic.List<string>, string)' with a call to 'string.Replace(string, string?, System.StringComparison)'. (https://msdn.microsoft.com/en-us/library/bb386080.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/SourceBuild.cs(63,37): warning CA2234: Modify 'SourceBuild.GetNuGetConfigAsync(Version)' to call 'HttpClient.GetStringAsync(Uri)' instead of 'HttpClient.GetStringAsync(string)'. (https://msdn.microsoft.com/en-us/library/ms182360.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/NuGet.cs(38,35): warning CA1822: Member GenerateNuGetConfig does not access instance data and can be marked as static (Shared in VisualBasic) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/SourceBuild.cs(44,33): warning CA2234: Modify 'SourceBuild.GetProdConFeedAsync(Version)' to call 'HttpClient.GetStringAsync(Uri)' instead of 'HttpClient.GetStringAsync(string)'. (https://msdn.microsoft.com/en-us/library/ms182360.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/SourceBuild.cs(46,40): warning CA2234: Modify 'SourceBuild.GetProdConFeedAsync(Version)' to call 'HttpClient.GetAsync(Uri)' instead of 'HttpClient.GetAsync(string)'. (https://msdn.microsoft.com/en-us/library/ms182360.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Program.cs(117,40): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Program.cs(132,33): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Test.cs(61,23): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Test.cs(66,36): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestOutputFormat.cs(149,28): warning CA1822: Member RemoveInvalidXmlCharacters does not access instance data and can be marked as static (Shared in VisualBasic) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Program.cs(156,48): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Program.cs(176,45): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Program.cs(192,34): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestOutputFormat.cs(105,58): warning CA1305: The behavior of 'int.ToString()' could vary based on the current user's locale settings. Replace this call in 'TestOutputFormats.JUnitOutput.AfterRunningAllTestsAsync(TestResults)' with a call to 'int.ToString(IFormatProvider)'. (https://msdn.microsoft.com/en-us/library/ms182190.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestOutputFormat.cs(106,61): warning CA1305: The behavior of 'int.ToString()' could vary based on the current user's locale settings. Replace this call in 'TestOutputFormats.JUnitOutput.AfterRunningAllTestsAsync(TestResults)' with a call to 'int.ToString(IFormatProvider)'. (https://msdn.microsoft.com/en-us/library/ms182190.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestOutputFormat.cs(18,32): warning CA1305: The behavior of 'string.Format(string, object)' could vary based on the current user's locale settings. Replace this call in 'TestOutputFormats.NewOutput.AfterParsingTestAsync(string, bool)' with a call to 'string.Format(IFormatProvider, string, params object[])'. (https://msdn.microsoft.com/en-us/library/ms182190.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestRunner.cs(73,19): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Program.cs(218,27): warning CA1308: In method 'CreateTraits', replace the call to 'ToLowerInvariant' with 'ToUpperInvariant'. (https://msdn.microsoft.com/en-us/library/bb386042.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestRunner.cs(94,23): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestRunner.cs(97,40): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestRunner.cs(106,23): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestRunner.cs(126,27): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestRunner.cs(132,40): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestRunner.cs(150,23): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestRunner.cs(153,19): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Program.cs(235,31): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Program.cs(238,30): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestParser.cs(101,22): warning CA1822: Member VersionMatches does not access instance data and can be marked as static (Shared in VisualBasic) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Program.cs(261,26): warning CA2007: Do not directly await a Task without calling ConfigureAwait [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/TestParser.cs(18,144): warning CA1801: Parameter testConfiguration of method TryParseAsync is never used. Remove the parameter or use it in the method body. (https://msdn.microsoft.com/en-us/library/ms182268.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/Program.cs(199,89): warning CA1801: Parameter sdkVersion of method CreateTraits is never used. Remove the parameter or use it in the method body. (https://msdn.microsoft.com/en-us/library/ms182268.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
dotnet-bunny/Turkey/NuGet.cs(28,59): warning CA1801: Parameter name of method IsPackageLiveAsync is never used. Remove the parameter or use it in the method body. (https://msdn.microsoft.com/en-us/library/ms182268.aspx) [dotnet-bunny/Turkey/Turkey.csproj]
```

cc @omajid

### PR DESCRIPTION
**Pull request by nicrowe00**
A fix for the test runner that patches most of the warnings that are reported in the terminal when compiling the test runner. Some warnings were suppressed as it was too time-consuming or there were impacts to other parts of the test runner when they were fixed.

Fixes #83

### CODE REVIEW

**Comment by nicrowe00** [comment]
CentOS 9 and 10 are unrelated to this PR.

File: Turkey/Test.cs [hunk 1]
```diff
@@ -18,8 +18,10 @@ public class TestDescriptor
         public string Type { get; set; }
         public bool Cleanup { get; set; }
         public double TimeoutMultiplier { get; set; } = 1.0;
-        public List<string> IgnoredRIDs { get; set; } = new();
-        public List<string> SkipWhen { get; set; } = new();
+#pragma warning disable CA1051 // Do not declare visible instance fields
+        public List<string> IgnoredRIDs = new();
```
Comment (tmds) [inline Turkey/Test.cs:22]: Add a `{get; set;}` so these become properties instead of instance fields. Then you can omit the warning supressions.

File: Turkey/Program.cs [hunk 2]
```diff
@@ -12,7 +12,9 @@
 
 namespace Turkey
 {
+#pragma warning disable CA1052 // Static holder types should be Static or NotInheritable
     public class Program
+#pragma warning restore CA1052 // Static holder types should be Static or NotInheritable
```
Comment (tmds) [inline Turkey/Program.cs:17]: Why not add the `static` modifier instead of suppressing these warnings?

File: Turkey/PlatformId.cs [hunk 3]
```diff
@@ -18,7 +18,9 @@ public List<string> CurrentIds
 
         public List<string> ComputePlatformIds(string[] osReleaseLines, string lddVersionOutput)
         {
+#pragma warning disable CA1308 // Normalize strings to uppercase
```
Comment (tmds) [inline Turkey/PlatformId.cs:21]: I've never had this warning. Do we have some specific analyzer settings?

Anyway, I'd simplify this code to (which probably won't get rid of the warning):
```cs
string arch = RuntimeInformation.OSArchitecture.ToString().ToLowerInvariant();
```
Or if you want to do something fancy:
```cs
static class EnumExtensionMethods
{
    public static string ToLowerInvariant(this Enum e)
        => e.ToString().ToLowerInvariant();
}
```

File: Turkey/NuGet.cs [hunk 4]
```diff
@@ -21,24 +21,33 @@ public NuGet(HttpClient client)
...
 
-        public async Task<string> GenerateNuGetConfig(List<string> urls, string nugetConfig = null)
+#pragma warning disable CA1822 // Mark members as static
+        public Task<string> GenerateNuGetConfig(List<string> urls, string nugetConfig = null)
+#pragma warning restore CA1822 // Mark members as static
         {
             if( !urls.Any() && nugetConfig == null )
+#pragma warning disable CA2208 // Instantiate argument exceptions correctly
                 throw new ArgumentNullException();
+#pragma warning restore CA2208 // Instantiate argument exceptions correctly
```
Comment (tmds) [inline Turkey/NuGet.cs:50]:
```
if (!urls.Any())
   ArgumentNullException.ThrowIfNull(nugetConfig);
```

File: Turkey/Cleaner.cs [hunk 5]
```diff
@@ -36,7 +36,9 @@ public static IEnumerable<string> LocalProjectCruft()
             yield return "project.lock.json";
         }
 
-        public async Task CleanProjectLocalDotNetCruftAsync()
+#pragma warning disable CA1822 // Mark members as static
```
Comment (tmds) [inline Turkey/Cleaner.cs:39]: Similar to https://github.com/redhat-developer/dotnet-bunny/pull/91/files#r1888234678, I'm not used to seeing this message though I often don't add the `static` keyword to members that are not using instance members. I wonder if we have some specific analyser settings that trigger this?

**Comment by tmds** [comment]
@nicrowe00 thanks for tacking this! Some of the changes you are making made me wonder if the analyzers you are fixing against are more strict than what I'm used to. I see there are some analyser references being made:

https://github.com/redhat-developer/dotnet-bunny/blob/116605a69c423b737e31c61d62f37c4ed30ea280/Turkey/Turkey.csproj#L17-L19

If we want to keep these analyzers but don't want to strictly apply every rule (for example requiring the `static`) then we can suppress those at the project level or introducing an editorconfig file.

File: Turkey/Program.cs (hunk 2 above)
Comment (nicrowe00) [reply Turkey/Program.cs:17]: This causes errors elsewhere if set to static.

**Comment by nicrowe00** [comment]
Current CI failures are due to release-version-sane, most OS' don't have the latest .NET version yet.

File: Turkey/PlatformId.cs [hunk 6]
```diff
@@ -63,25 +65,27 @@ public List<string> ComputePlatformIds(string[] osReleaseLines, string architect
...
+            if (text.StartsWith("\"", StringComparison.Ordinal) && text.EndsWith("\"", StringComparison.Ordinal))
             {
                 return text.Substring(1, text.Length - 2);
             }
 
             return text;
         }
 
+#pragma warning disable CA1822 // Mark members as static
         internal string GetLddVersion()
```
Comment (omajid) [inline Turkey/PlatformId.cs:87]: Other methods are now `static`, so I am okay with marking this as `static` too.

File: Turkey/TestParser.cs [hunk 7]
```diff
@@ -32,12 +35,12 @@ public class TestParser
...
                     test = new XUnitTest(directory, system, nuGetConfig, descriptor, enabled);
-                    return (true, test);
+                    return Task.FromResult((true, test));
                 case "bash":
                     test = new BashTest(directory, system, nuGetConfig, descriptor, enabled);
-                    return (true, test);
+                    return Task.FromResult((true, test));
                 default:
-                    return (false, null);
+                    return Task.FromResult((false, test));
```
Comment (omajid) [inline Turkey/TestParser.cs:43]:
```suggestion
                    return Task.FromResult((false, null));
```

Comment (nicrowe00) [reply Turkey/TestParser.cs:43]: Setting it this way causes an error when compiling. Task.FromResult can't use null as an argument. test is set to null by default so it's the same as if null was used and Task.FromResult accepts test as an argument.

File: Turkey/PlatformId.cs (hunk 6 above)
Comment (nicrowe00) [reply Turkey/PlatformId.cs:87]: Setting this to static causes an error when executing `dotnet test -f net6.0 -c Release --verbosity detailed Turkey.Tests`

Error: `Turkey.Tests/PlatformIdTest.cs(34,30): error CS0176: Member 'PlatformId.GetLddVersion()' cannot be accessed with an instance reference; qualify it with a type name instead`

File: Turkey/TestParser.cs (hunk 7 above)
Comment (tmds) [reply Turkey/TestParser.cs:43]: This method can probably be made non-async.

> Task.FromResult can't use null as an argument

You mean: it can't figure out what type the `null` should be. You can make that explicit by using `(Test)null` (or `(Test?)null` in nullable enabled code).

Comment (nicrowe00) [reply Turkey/TestParser.cs]: Ah OK, my mistake.

**Comment by tmds** [comment]
@nicrowe00 If you think there are no regressions and this reduces the nr of warnings, go ahead and merge!

**Comment by nicrowe00** [comment]
I re-ran the checks here: https://github.com/nicrowe00/dotnet-bunny/actions/runs/15134934565, only failures are due to release-version-sane.
